version: '3.8'

services:
  pesito:
    image: orellanamatias/pesito:latest
    container_name: pesito
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/db
    environment:
      - PORT=3000
      - NODE_ENV=production
